### ISSUE TITLE
Breaking change on older node versions

### ISSUE THREAD

**Issue by peshrawahmed** [elastic/elasticsearch-js#1193]
## 🐛 Bug Report

I am currently using nodejs v9.5 and getting error on new client version v7.7.0 that has been released hours ago. I don't know if it is done intentionally or not(Sorry if it is done intentionally). But seems like older node versions does not work with the following declaration of generator functions:

```
async * FunctionName(){}
``` 

giving me error on `lib/Helpers.js` on line 56: 

```
  async * scrollSearch (params, options = {}) {
        ^
```
## To Reproduce

Running on an older version on node reproduces the error.
Adding the error screenshot
![22](https://user-images.githubusercontent.com/35446007/81924036-39ec6880-95e7-11ea-8f0c-9356039ca333.jpeg)
## Your Environment

- *node version*: 9.5
- `@elastic/elasticsearch` *version*: >=7.7.0
- *os*: Mac

**Comment by delvedor** [comment]
Hello! You are right, the recently introduced [Helpers](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-helpers.html) require a special flag for Node v8.
Unfortunately, even if you are not using them, this will break your code.

I'm working on a fix for the issue.

**Comment by delvedor** [comment]
I've just released `v7.7.1` on npm with the fix, thank you for reporting!
I would also **strongly** recommend migrating to a supported version of Node.js, as using an unsupported version could expose you to severe security risks.
You can find the officially supported versions of Node.js [here](https://nodejs.org/en/about/releases/).

**Comment by peshrawahmed** [comment]
> I would also **strongly** recommend migrating to a supported version of Node.js, as using an unsupported version could expose you to severe security risks.
Yes we have plan to migrate. Thank you for the fix.

**Comment by delvedor** [comment]
Hello! Plase take a look at out [Node.js support](https://github.com/elastic/elasticsearch-js#nodejs-support) table, both Node v8 and v10 are no longer supported.
I would also **strongly** recommend migrating to a supported version of Node.js, as using an unsupported version could expose you to severe security risks.
You can find the officially supported versions of Node.js [here](https://nodejs.org/en/about/releases/).

**Comment by fahamakhanKlabs** [comment]
Hey! Still facing this issue. Although I've updated node.js version, I also tried multiple LTS versions of node.js to go with but the error persists. Using node.js version v16.13.0 and elasticsearch version 7.13.0.
Please help out as soon as possible.

**Comment by peshrawahmed** [comment]
> Hey! Still facing this issue. Although I've updated node.js version, I also tried multiple LTS versions of node.js to go with but the error persists. Using node.js version v16.13.0 and elasticsearch client version 7.13.0 and elasticsearch version 7.10 OS Ubuntu Please help out as soon as possible.

May sound silly but can you remove node_modules and package-lock files and run `npm i` again. 

and also can you run `node -v` to double check if you are using the right version.

**Comment by fahamakhanKlabs** [comment]
still not wokring showing the same error again that is

/var/www/terravigil/node_modules/@elastic/elasticsearch/lib/Helpers.js:75
  async * scrollSearch (params, options = {}) {
        ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/var/www/terravigil/node_modules/ts-node/src/index.ts:1361:43)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

Nodejs version  v16.13.0

**Comment by fahamakhanKlabs** [comment]
Working. Thanks :)
