### ISSUE TITLE
ERROR in ...lib/utils.js Module not found: Error: Can't resolve 'path' in '.../node_modules/elasticsearch/src/lib'

### ISSUE THREAD

**Issue by Son-Lam** [elastic/elasticsearch-js#661]
Hello,

I am first time Elasticsearch user. I am trying to use it in my Angular 6 project (Angular 6, Rxjs 6, Node 10.1.0). I am getting this error while compiling:

ERROR in ./node_modules/elasticsearch/src/lib/utils.js
Module not found: Error: Can't resolve 'path' in '/.../node_modules/elasticsearch/src/lib'.

Could you help to resolve it.

Best Regards,

**Comment by YoannBureau** [comment]
Got the same problem here, pretty curious how to solve this.

**Comment by spalger** [comment]
Do either of you have time to create a reproduction project that I can use to debug? I'm unfamiliar with Angular 2+ and would take a while to get to the point of debugging this.

**Comment by Son-Lam** [comment]
[poc-elasticsearch.zip](https://github.com/elastic/elasticsearch-js/files/2002018/poc-elasticsearch.zip)

Thanks @spalger ,

I attached here a short Angular 6 project. Here is the instruction how to re-produce the issue:

1. Install NodeJs 10.1.0
2. Install Angular CLI by running: `npm install -g @angular/cli`
3. extract the attached zip file
4. `cd poc-elasticsearch`
5. `npm install`
6. `ng serve --open`

You will get this log in command line:
```
Date: 2018-05-14T18:02:04.806Z
Hash: 65e95cc0b40537195983
Time: 6149ms
chunk {main} main.js, main.js.map (main) 14 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.4 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 15.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 5.55 MB [initial] [rendered]

ERROR in ./node_modules/elasticsearch/src/lib/utils.js
Module not found: Error: Can't resolve 'path' in '/Users/solam/workspaces/pocs/poc-elasticsearch/node_modules/elastic
```

Please let me know if you see any problem.

Thanks a lot,

Son Lam.

**Comment by YoannBureau** [comment]
@Son-lan that is what we call a message percussion :)
See my comment for the solution.

**Comment by Son-Lam** [comment]
@spalger ,

👍 :-) it is good that it takes only few minutes to create the test case.

I tried your solution but it does not seem to fix my problem. My code is very simple:
```
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import * as elasticsearch from 'elasticsearch';

@Injectable()
export class ElasticSearchService {
    private _client: elasticsearch.Client;

    constructor() {
        if (!this._client) this._connect();
    }

    private _connect() {
        this._client = new elasticsearch.Client({
            host: 'http://localhost:9200',
            log: 'trace'
        });
    }

    search(value): any {
        if (value) {
            console.log(value);
            return this._client.search({
                index: 'blog',
                q: `title:${value}`
            });
        } else {
            return Promise.resolve({});
        }
    }

    addToIndex(value): any {
        return this._client.create(value);
    }

    isAvailable(): any {
        const pp: elasticsearch.PingParams = {
            requestTimeout: Infinity,
            body: 'Hello elasticsearch!'
        };

        return this._client.ping(pp);
    }
}
```

Could take another look?

Thanks,

Son Lam.

**Comment by YoannBureau** [comment]
@Son-Lam are you sure you don't have any other references to elasticsearch somewhere else in your code? I've copy/pasted your service in my project and it does compile:
![image](https://user-images.githubusercontent.com/16898224/40044514-d7be6cca-5827-11e8-9425-cb1d571b9cdc.png)

**Comment by Son-Lam** [comment]
@spalger , Thanks a lot for looking into it.

Could you check what version of NodeJs do you have?

Thanks,

**Comment by YoannBureau** [comment]
@Son-Lam looks like it's a cli problem, not only with path. Many people are having troubles right now: https://github.com/angular/angular-cli/issues/10681

I tried this solution but didn't worked: https://github.com/angular/angular-cli/issues/10681#issuecomment-388065383

**Comment by Son-Lam** [comment]
@YoannBureau , I have upgraded to version 15.0.0 and the error went away 👍 .

Could you try and confirm it has been fixed for you too?

**Comment by Son-Lam** [comment]
Solution: upgrade to version 15.0.0.

**Comment by bjdivakar** [comment]
@Son-Lam which package you upgraded to 15.0.0

**Comment by praveenwala** [comment]
Upgrading to 15.0.0  doesn't solve my problem. Any Other Solution? @Son-Lam 



![screen shot 2018-07-06 at 5 13 01 pm](https://user-images.githubusercontent.com/5037140/42377197-ef52eb0e-813f-11e8-94f3-55291c7ec12c.png)

**Comment by Generalomosco** [comment]
Install the require dependencies using this line below
`npm i --save util events lodash`

**Comment by niazlake** [comment]
> Install the require dependencies using this line below
> `npm i --save util events lodash url querystring util events lodash url querystring http https agentkeepalive zlib`

this didnt help me

**Comment by demisx** [comment]
Installing deps made a couple of similar errors to go away for me, but not all of them. :(
